### ISSUE TITLE
Set starting point (ignore z/height)?

### ISSUE THREAD

**Issue by Kyli3Boi** [Bara/fuckZones#67]
![image](https://user-images.githubusercontent.com/64275139/98420466-ecc9ea80-208f-11eb-8c07-bc65269554a4.png)

I dont really understand the need for this, especially that you are only able to select it once you have already placed a starting point. If i have already placed a starting point on the ground why would i need to aim in the air and then replace the starting point on the ground?

I dont think i have ever been in a situation where i would have used this...

**Comment by Bara** [comment]
> Understood but if I have already placed the point then why place another one? 
> 
> I really dont think there Is any use for this. Just something to think about 

For not losing the z position, which can be annoying
