### ISSUE TITLE
Poly zone not obeying color

### ISSUE THREAD

**Issue by Kyli3Boi** [Bara/fuckZones#74]
Poly zone color is orange and will not change
![image](https://user-images.githubusercontent.com/64275139/100322896-9801fb80-2fcd-11eb-9513-3d9cd8cc0cf3.png)

**Comment by Bara** [comment]
You're in the edit zone menu, that's normal and should become normal when you close/leave this menu for the specific zone.

**Comment by Kyli3Boi** [comment]
xD hahah brain was off
