### ISSUE TITLE
Check if inside zone without case sensitive and with StrContains

### ISSUE THREAD

**Issue by eyal282** [Bara/fuckZones#99]
Title, I want a native to check if player is in a zone by StrContains.

**Comment by Bara** [comment]
Feel free to modify [fuckZones_IsClientInZone](https://github.com/Bara/fuckZones/blob/d4fa234c00e9704c6c82d2a2d1b2c84e7d944af4/addons/sourcemod/scripting/fuckZones.sp#L5342) or add a new native which based on fuckZones_IsClientinZone.

**Comment by eyal282** [comment]
Done in a PR.
